export const PublicRoutes = {
  LOGIN: "/",
  SIGNUP: "/signup",
  HOME: "/home",
  SEARCH: "/search",
  USER: "/user",
  ALBUM: "/album/:albumid",
  SONG: "/song",
  PLAYLISTS: "/playlists",
  SELECTEDPLAYLISTS: "/playlist/:playlistid",
  AUDIOPLAYER: "/audioPlayer",
  MYSONGS: "/mySongs",
  EDITPROFILE: "/editprofile",
  UPLOAD: "/upload",
};
